model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: segmentation
    image_size: 64
    channels: 4
    concat_mode: true
    cond_stage_trainable: true
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 7 ##CHANGE
        out_channels: 4
        model_channels: 128
        attention_resolutions:
        - 16
        - 8
        - 4
        num_res_blocks: 2
        channel_mult:
        - 1
        - 4
        - 8
        num_heads: 8

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        #n_embed: 8192
        ckpt_path: logs\KLAE_64x64x4_rgba_sat_and_elevation_NO_AUG\checkpoints\epoch=000053.ckpt #configs/first_stage_models/vq-f4/model.ckpt #models/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 4
          out_ch: 4
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity




    # first_stage_config:
    #   target: ldm.models.autoencoder.VQModelInterface
    #   params:
    #     embed_dim: 3
    #     n_embed: 8192
    #     ckpt_path: configs/first_stage_models/vq-f4/model.ckpt #models/first_stage_models/vq-f4/model.ckpt
    #     ddconfig:
    #       double_z: false
    #       z_channels: 3
    #       resolution: 256
    #       in_channels: 3
    #       out_ch: 3
    #       ch: 128
    #       ch_mult:
    #       - 1
    #       - 2
    #       - 4
    #       num_res_blocks: 2
    #       attn_resolutions: []
    #       dropout: 0.0
    #     lossconfig:
    #       target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.SpatialRescaler
      params:
        n_stages: 2
        in_channels: 3 #182 putetre pour one-hot label
        out_channels: 3

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4 #48
    num_workers: 2
    wrap: True
    train:
      target: ldm.data.terrain.TerrainSegmentationTrain
      params:
        size: 256
        rgba: True
        # augment: True
    validation:
      target: ldm.data.terrain.TerrainSegmentationValidation
      params:
        size: 256
        rgba: True
    test:
      target: ldm.data.terrain.TerrainSegmentationTest
      params:
        size: 256
        rgba: True


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 10000
        max_images: 8
        increase_log_steps: False
        log_first_step: True

  trainer:
    benchmark: True