model:
  base_learning_rate: 1.0e-04 #5.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 32 # try 64 as in sd-v2
    channels: 4
    cond_stage_trainable:  False # Change to false if frozenCLIP
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: True # we set this to false when the config is used for inference

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 224 # this was 320 but can't work with that
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        # channel_mult: [ 1, 2, 4, 4 ]
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_heads: 8
        # num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        # use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 768
        # context_dim: 1024 FOR OPEN CLIP EMBEDDER
        use_checkpoint: True
        legacy: False
        # use_fp16: True -> Probably only for inference

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ckpt_path: configs/first_stage_models/kl-f8/model.ckpt 
        ddconfig:
          #attn_type: "vanilla-xformers"
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

    # From SD-2
    # cond_stage_config:
    #   target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
    #   params:
    #     freeze: True
    #     layer: "penultimate"

    # cond_stage_config:
    #   target: ldm.modules.encoders.modules.BERTEmbedder
    #   params:
    #     n_embed: 768 #1280 #
    #     n_layer: 32

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2 #48
    num_workers: 2
    wrap: True
    train:
      target: ldm.data.coco.CocoImagesAndCaptionsTrain
      params:
        size: 256
    validation:
      target: ldm.data.coco.CocoImagesAndCaptionsValidation
      params:
        size: 256


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 20000
        max_images: 4
        increase_log_steps: False
        # log_first_step: True
